export const JUDETE_ROMANIA = [
  "Alba",
  "Arad",
  "Argeș",
  "Bacău",
  "Bihor",
  "Bistrița-Năsăud",
  "Botoșani",
  "Brașov",
  "Brăila",
  "București",
  "Buzău",
  "Caraș-Severin",
  "Călărași",
  "Cluj",
  "Constanța",
  "Covasna",
  "Dâmbovița",
  "Dolj",
  "Galați",
  "Giurgiu",
  "Gorj",
  "Harghita",
  "Hunedoara",
  "Ialomița",
  "Iași",
  "Ilfov",
  "Maramureș",
  "Mehedinți",
  "Mureș",
  "Neamț",
  "Olt",
  "Prahova",
  "Satu Mare",
  "Sălaj",
  "Sibiu",
  "Suceava",
  "Teleorman",
  "Timiș",
  "Tulcea",
  "Vaslui",
  "Vâlcea",
  "Vrancea",
];

export const TIPURI_SERVICII = [
  "Asistență medicală",
  "Asistență socială",
  "Cazare permanentă",
  "Cazare temporară",
  "Recuperare și reabilitare",
  "Servicii pentru demență/Alzheimer",
  "Servicii pentru persoane cu dizabilități",
  "Îngrijire paliativă",
  "Fizioterapie",
  "Activități recreative",
  "Alimentație proprie",
  "Transport",
];
