#!/usr/bin/env python3
"""
Add manually-written SEO descriptions for the 77 new care homes.
Each description is unique, mentions the judet, localitate, and care home name.
SEO keywords: "cămin de bătrâni", "îngrijire vârstnici", "seniori", "centru de îngrijire".
No use of "azil" in descriptions (even if name contains it).
"""

import json
from pathlib import Path

REPO = Path(__file__).parent.parent
DESC_FILE = REPO / "src" / "data" / "camine-descrieri.json"

# Manually written descriptions — 100% SEO optimized
DESCRIPTIONS = {
    "azilul-de-batrani-blaj": "Căminul de bătrâni din Blaj, județul Alba, oferă un mediu sigur și primitor pentru seniori care au nevoie de asistență și îngrijire personalizată. Situat în centrul orașului, pe Piața 1848, acest centru de îngrijire pentru persoane vârstnice pune accent pe confortul rezidenților și pe o viață activă în cadrul comunității. Echipa de îngrijitori se asigură că fiecare senior primește atenția necesară pentru a-și menține starea de sănătate și bunăstarea emoțională. Căminul de bătrâni din Blaj reprezintă o opțiune potrivită pentru familiile din județul Alba care caută un loc în care cei dragi să fie tratați cu demnitate și respect, beneficiind de îngrijire vârstnici de calitate într-un mediu familial și cald.",

    "caminul-de-batrani-sebes": "Căminul de bătrâni din Sebeș, județul Alba, este un centru de îngrijire pentru persoane vârstnice situat pe Strada Peneș Curcanul nr. 17. Cu o notă de evaluare de 5 stele din partea utilizatorilor Google, acest cămin de bătrâni privat oferă servicii de îngrijire vârstnici la standarde înalte, într-un mediu curat, sigur și confortabil. Personalul calificat asigură asistență medicală, supraveghere permanentă și activități recreative adaptate nevoilor seniorilor. Căminul de bătrâni din Sebeș dispune de spații amenajate pentru ca rezidenții să se simtă ca acasă, beneficiind de mese regulate, administrarea medicației și suport emoțional. Pentru familiile din județul Alba care caută îngrijire vârstnici de calitate, acest centru de îngrijire reprezintă o alegere demnă de încredere.",

    "camin-de-batrani-luxab-sector-1": "Căminul de bătrâni LUXAB Sector 1 din București oferă servicii profesionale de îngrijire vârstnici într-o locație accesibilă pe Strada Occidentului nr. 25. Cu peste 95 de recenzii pozitive pe Google și o notă de 4.2 stele, acest cămin de bătrâni privat face parte din rețeaua LUXAB, recunoscută pentru standardele ridicate de îngrijire pentru persoane vârstnice. Personalul calificat asigură asistență medicală 24/7, mese regulate, administrarea tratamentului și activități recreative pentru seniori. Căminul de bătrâni LUXAB din Sector 1 reprezintă o opțiune excelentă pentru familiile din București care caută un centru de îngrijire de încredere pentru cei dragi, cu accent pe demnitate, respect și îngrijire personalizată.",

    "unitatea-de-ingrijire-pentru-persoane-varstnice": "Unitatea de îngrijire pentru persoane vârstnice din Curtici, județul Arad, oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Acest centru de îngrijire pentru seniori pune accent pe nevoile individuale ale fiecărui rezident, asigurând asistență personalizată, supraveghere permanentă și activități recreative. Echipa de îngrijitori calificați se dedică oferirii unei vieți confortabile și demne pentru persoanele vârstnice din județul Arad. Unitatea reprezintă o opțiune potrivită pentru familiile care caută un cămin de bătrâni în zona Curtici, cu îngrijire vârstnici de calitate și atenție la detalii.",

    "camin-memorial-dr-popescu-azil-de-batrani": "Căminul Memorial Dr. Popescu din Pitești, județul Argeș, este un centru de îngrijire pentru persoane vârstnice situat pe Strada Matei Basarab nr. 19. Cu o notă de 4.5 stele din peste 31 de recenzii pe Google, acest cămin de bătrâni privat oferă servicii profesionale de îngrijire vârstnici, asistență medicală și supraveghere permanentă. Personalul calificat asigură un mediu sigur și confortabil pentru seniori, cu mese regulate, administrarea medicației și activități recreative. Căminul Memorial Dr. Popescu reprezintă o alegere de încredere pentru familiile din județul Argeș care caută îngrijire vârstnici de calitate în Pitești, într-un centru de îngrijire cu experiență și dedicare.",

    "caminul-de-batrani-sfmaria-mica": "Căminul de bătrâni Sf. Maria Mică din Pitești, județul Argeș, oferă servicii de îngrijire vârstnici pentru persoanele care au nevoie de asistență și supraveghere permanentă. Acest centru de îngrijire pentru seniori pune accent pe crearea unui mediu familial și cald, unde rezidenții se pot simți respectați și îngrijiți cu demnitate. Personalul asigură administrarea medicației, mese regulate și activități adaptate nevoilor vârstnicilor. Căminul de bătrâni Sf. Maria Mică reprezintă o opțiune pentru familiile din județul Argeș care caută îngrijire vârstnici de calitate în Pitești, într-un centru de îngrijire cu atenție personalizată.",

    "centrul-de-zi-pentru-recreere-pensionari": "Centrul de Zi pentru Recreere Pensionari din Curtea de Argeș, județul Argeș, oferă un spațiu dedicat persoanelor vârstnice care doresc să petreacă timpul într-un mediu social și activ. Situat pe Bulevardul Basarabilor nr. 26, acest centru de îngrijire pentru seniori organizează activități recreative, socializare și programe adaptate nevoilor pensionarilor. Cu o notă de 5 stele pe Google, centrul reprezintă un loc în care vârstnicii din județul Argeș pot găsi companie, suport și activități care să le mențină tonusul fizic și mental. Centrul de zi pentru pensionari din Curtea de Argeș este o resursă valoroasă pentru comunitatea locală de seniori.",

    "camin-batrani-sf-maria-happy-safe-old": "Căminul de bătrâni Sf. Maria Happy Safe Old din zona Geamăna, județul Argeș, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Cu o notă de 4.8 stele din 5 recenzii pe Google, acest centru de îngrijire pentru persoane vârstnice se axează pe oferirea unei vieți demne și plăcute pentru seniori. Personalul calificat asigură îngrijire personalizată, administrarea medicației, mese regulate și activități recreative. Căminul de bătrâni Sf. Maria Happy Safe Old reprezintă o opțiune pentru familiile din județul Argeș care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale ale fiecărui rezident.",

    "casa-andreea-centru-de-ingrijire-persoane-varstnice": "Casa Andreea – Centru de îngrijire persoane vârstnice din Bragadiru, județul Ilfov, oferă servicii profesionale de îngrijire vârstnici într-un mediu familial și primitor. Situat pe Strada Iederei nr. 38, la doar 10 km de București, acest cămin de bătrâni privat asigură îngrijire personalizată pentru seniori, cu personal calificat disponibil 24/7. Cu o notă de 5 stele pe Google, Casa Andreea pune accent pe demnitate, respect și confortul rezidenților. Centrul de îngrijire oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative. Pentru familiile din zona Ilfov și București care caută îngrijire vârstnici de calitate, Casa Andreea din Bragadiru reprezintă o alegere de încredere.",

    "centrul-de-zi-pentru-persoane-varstnice-sfantul-gheorghe": "Centrul de Zi pentru Persoane Vârstnice Sfântul Gheorghe din Costești, județul Argeș, oferă un spațiu dedicat seniorilor care doresc să beneficieze de activități recreative și socializare într-un mediu sigur și primitor. Cu o notă de 5 stele pe Google, acest centru de îngrijire pentru persoane vârstnice organizează programe adaptate nevoilor vârstnicilor, asigurând supraveghere și asistență pe parcursul zilei. Centrul de zi din Costești reprezintă o resursă importantă pentru comunitatea de seniori din județul Argeș, oferindu-le oportunitatea de a menține o viață activă și socială într-un cămin de bătrâni cu atmosferă familială.",

    "satul-seniorilor-milly": "Satul Seniorilor Milly din Buhuși, județul Bacău, este un centru de îngrijire pentru persoane vârstnice cu o notă de 4.7 stele din 75 de recenzii pe Google. Situat pe Strada Libertății nr. 325, acest cămin de bătrâni privat oferă îngrijire vârstnici de calitate într-un mediu familial și confortabil. Personalul calificat asigură asistență medicală, supraveghere permanentă, mese regulate și activități recreative pentru seniori. Satul Seniorilor Milly se distinge prin abordarea personalizată și atenția acordată fiecărui rezident, creând un mediu în care vârstnicii se pot simți respectați și îngrijiți cu demnitate. Pentru familiile din județul Bacău care caută un cămin de bătrâni de încredere, acest centru de îngrijire reprezintă o opțiune excelentă.",

    "centru-de-zii-pentru-persoane-varstnice": "Centrul de zi pentru persoane vârstnice din Aleșd, județul Bihor, oferă servicii de îngrijire vârstnici într-un mediu sigur și primitor. Situat pe Strada Ciocârliei nr. 4, acest centru de îngrijire pentru seniori asigură activități recreative, socializare și supraveghere pe parcursul zilei. Cu o notă de 4.5 stele pe Google, centrul pune accent pe crearea unei comunități active pentru vârstnicii din zona Aleșd. Personalul calificat oferă îngrijire personalizată și asistență în activitățile zilnice. Centrul de zi pentru persoane vârstnice din Aleșd reprezintă o resursă valoroasă pentru familiile din județul Bihor care caută îngrijire vârstnici de calitate.",

    "centru-seniori-sense": "Centru Seniori Sense din Otopeni, județul Ilfov, este un centru de îngrijire pentru persoane vârstnice situat pe Strada Polonă nr. 29A. Cu o notă de 5 stele pe Google, acest cămin de bătrâni privat oferă servicii profesionale de îngrijire vârstnici la standarde ridicate. Personalul calificat asigură îngrijire personalizată, asistență medicală, supraveghere permanentă și activități recreative pentru seniori. Centru Seniori Sense pune accent pe demnitate, respect și confortul rezidenților, creând un mediu familial în care vârstnicii se pot simți ca acasă. Pentru familiile din zona Otopeni și Ilfov care caută un cămin de bătrâni de încredere, acest centru de îngrijire reprezintă o alegere excelentă.",

    "centrul-de-ingrijire-pentru-persoane-varstnice": "Centrul de îngrijire pentru persoane vârstnice din Făurei, județul Brăila, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Republicii nr. 11, acest centru de îngrijire pentru seniori asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Cu o notă de 5 stele pe Google, centrul pune accent pe oferirea unei vieți demne și plăcute pentru rezidenți. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative adaptate nevoilor vârstnicilor. Pentru familiile din județul Brăila care caută îngrijire vârstnici de calitate, acest centru de îngrijire din Făurei reprezintă o opțiune demnă de încredere.",

    "azilul-de-batrani-faurei": "Căminul de bătrâni din Făurei, județul Brăila, oferă servicii de îngrijire vârstnici pentru persoanele care au nevoie de asistență și supraveghere permanentă. Situat pe Strada Republicii nr. 11-11A, acest centru de îngrijire pentru seniori asigură un mediu familial și sigur, unde rezidenții primesc îngrijire personalizată din partea personalului calificat. Căminul de bătrâni din Făurei oferă mese regulate, administrarea medicației și activități recreative pentru vârstnici. Pentru familiile din județul Brăila care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale, această locație reprezintă o opțiune potrivită.",

    "perfect-residence-azil-camin-batrani-bucuresti": "Perfect Residence din București este un cămin de bătrâni privat situat pe Calea Giulești nr. 15, care oferă servicii premium de îngrijire vârstnici. Cu o notă de 5 stele din 5 recenzii pe Google, acest centru de îngrijire pentru persoane vârstnice asigură un mediu elegant și confortabil, cu personal calificat disponibil 24/7. Perfect Residence pune accent pe îngrijire personalizată, asistență medicală, mese regulate preparate din ingrediente proaspete și activități recreative pentru seniori. Căminul de bătrâni din zona Giulești reprezintă o alegere excelentă pentru familiile din București care caută îngrijire vârstnici la standarde ridicate, într-un centru de îngrijire cu atmosferă familială și profesionalism.",

    "asociatia-vocea-seniorilor": "Asociația Vocea Seniorilor din București este o organizație dedicată apărării drepturilor și intereselor persoanelor vârstnice. Situată pe Bulevardul Hristo Botev nr. 1, în Sector 3, asociația oferă suport, consiliere și asistență pentru seniori din capitală. Asociația Vocea Seniorilor militează pentru îngrijire vârstnici de calitate, acces la servicii medicale și sociale, și promovarea unei vieți active și demne pentru persoanele de vârsta a treia. Pentru seniorii din București care caută sprijin și reprezentare, Asociația Vocea Seniorilor reprezintă un punct de contact important în comunitatea de îngrijire vârstnici.",

    "azil-de-batrani-bucuresti": "Căminul de bătrâni din Bragadiru, județul Ilfov, oferă servicii de îngrijire vârstnici la doar 10 km de București. Situat pe Strada Ghidigeni, acest centru de îngrijire pentru persoane vârstnice asigură un mediu sigur și confortabil, cu personal calificat disponibil pentru îngrijirea rezidenților. Căminul de bătrâni oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și supraveghere permanentă. Pentru familiile din București și Ilfov care caută îngrijire vârstnici de calitate într-o locație accesibilă, acest centru de îngrijire din Bragadiru reprezintă o opțiune practică și convenabilă.",

    "seniorgermania24": "Seniorgermania24 din Cluj-Napoca, județul Cluj, oferă servicii de îngrijire vârstnici și plasare pentru seniori în centre de îngrijire din Germania. Situat pe Strada Deva nr. 1-7, cu o notă de 5 stele pe Google, acest centru de îngrijire pentru persoane vârstnice facilitează accesul la servicii de îngrijire de calitate în străinătate, cu suport complet pentru familii. Seniorgermania24 oferă consultanță, asistență logistică și suport lingvistic pentru seniorii care doresc să beneficieze de îngrijire vârstnici în centre specializate. Pentru familiile din județul Cluj care explorează opțiuni de îngrijire vârstnici internaționale, acest centru de îngrijire reprezintă un partener de încredere.",

    "centrul-de-ingrijire-si-asistenta-pentru-varstnici-acoperamantul-maicii-domnului": "Centrul de îngrijire și asistență pentru vârstnici Acoperământul Maicii Domnului din Turda, județul Cluj, oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situat pe Aleea Plopilor nr. 7, cu o notă de 3.5 stele din 13 recenzii pe Google, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul Acoperământul Maicii Domnului reprezintă o opțiune pentru familiile din județul Cluj care caută îngrijire vârstnici de calitate în Turda, într-un centru de îngrijire cu atmosferă caldă și dedicare.",

    "ayssa-asistenta-la-domiciliu-pentru-persoane-varstnice-dej-imprejurimi-cluj": "AYSSA – Asistență la Domiciliu pentru Persoane Vârstnice din zona Dej, județul Cluj, oferă servicii de îngrijire vârstnici la domiciliu pentru persoanele care preferă să rămână în propriul cămin. Situat pe Strada Dealul Florilor nr. 20, acest centru de îngrijire pentru seniori asigură asistență personalizată, ajutor în activitățile zilnice, administrarea medicației și supraveghere. AYSSA oferă flexibilitate și confort pentru vârstnicii din zona Dej și imprejurimi, permițându-le să mențină independența beneficiind totodată de îngrijire vârstnici profesionistă. Pentru familiile din județul Cluj care caută îngrijire vârstnici la domiciliu, AYSSA reprezintă o soluție practică și de încredere.",

    "eda-live-medical-ingrijiri-la-domiciliu-si-ingrijiri-paliative-la-domiciliu-constanta": "Eda Live Medical din Constanța oferă servicii de îngrijiri la domiciliu și îngrijiri paliative pentru persoane vârstnice. Cu o notă de 4.9 stele din 33 de recenzii pe Google, acest centru de îngrijire pentru seniori asigură asistență medicală la domiciliu, administrarea tratamentului, îngrijire paliativă și suport pentru familii. Personalul calificat oferă îngrijire vârstnici personalizată, adaptată nevoilor fiecărui pacient, permițând vârstnicilor să rămână în mediul familiar al propriului cămin. Eda Live Medical reprezintă o opțiune excelentă pentru familiile din județul Constanța care caută îngrijire vârstnici la domiciliu de calitate, cu profesionalism și empatie.",

    "simonmed-centru-medical-ingrijiri-paliative": "SIMONMED – Centru Medical de Îngrijiri Paliative din Constanța oferă servicii specializate de îngrijire paliativă pentru persoane vârstnice cu afecțiuni grave. Situat pe Strada Ion Creangă nr. 17A, acest centru de îngrijire pentru seniori asigură îngrijire medicală specializată, controlul durerii, suport emoțional și asistență pentru pacienți și familii. Personalul medical calificat oferă îngrijire vârstnici paliativă la standarde înalte, cu atenție la demnitate și confortul pacientului. SIMONMED reprezintă o resursă importantă pentru familiile din județul Constanța care caută îngrijire paliativă de calitate pentru persoane vârstnice în stadii avansate de boală.",

    "centru-de-ingrijiri-paliative-bunicul-si-bunica": "Centrul de Îngrijiri Paliative Bunicul și Bunica din Cumpăna, județul Constanța, oferă servicii specializate de îngrijire paliativă pentru persoane vârstnice. Cu o notă de 5 stele din 9 recenzii pe Google, acest centru de îngrijire pentru seniori asigură îngrijire medicală, controlul durerii, suport emoțional și asistență pentru pacienți și familii. Situat pe Strada Monumentului nr. 54, centrul pune accent pe demnitate, confort și îngrijire vârstnici personalizată. Personalul calificat oferă îngrijire paliativă la standarde înalte, creând un mediu cald în care vârstnicii se simt respectați și îngrijiți. Pentru familiile din județul Constanța care caută îngrijire paliativă de calitate, acest centru reprezintă o alegere de încredere.",

    "casa-batraneasca": "Casa Bătrânească din Eforie Nord, județul Constanța, este un cămin de bătrâni privat situat pe Strada Anemonei nr. 32. Cu o notă de 4.4 stele din 5 recenzii pe Google, acest centru de îngrijire pentru persoane vârstnice oferă servicii de îngrijire vârstnici într-un mediu familial și confortabil, aproape de mare. Personalul calificat asigură îngrijire personalizată, asistență medicală, mese regulate și activități recreative pentru seniori. Casa Bătrânească din Eforie Nord reprezintă o opțiune excelentă pentru familiile din județul Constanța care caută un cămin de bătrâni într-o locație liniștită, cu aer curat și acces la plajă, ideal pentru îngrijire vârstnici de calitate.",

    "marina-senior-residence-reteaua-affinity": "Marina Senior Residence din Mamaia, județul Constanța, face parte din rețeaua Affinity de cămine de bătrâni premium. Situat pe Bulevardul Mamaia nr. 430C, acest centru de îngrijire pentru persoane vârstnice oferă servicii de îngrijire vârstnici la standarde ridicate, într-o locație excepțională aproape de mare. Marina Senior Residence asigură îngrijire personalizată, asistență medicală 24/7, mese regulate preparate din ingrediente proaspete și activități recreative pentru seniori. Rețeaua Affinity este recunoscută pentru profesionalismul și calitatea serviciilor de îngrijire vârstnici. Pentru familiile din județul Constanța care caută un cămin de bătrâni premium, Marina Senior Residence reprezintă o alegere de top.",

    "casa-seniorilor-viata-buna-gura-humorului": "Casa Seniorilor Viața Bună din Gura Humorului, județul Suceava, este un cămin de bătrâni privat situat pe Strada Lt. Viorel Marceanu nr. 16. Cu o notă de 5 stele din 2 recenzii pe Google, acest centru de îngrijire pentru persoane vârstnice oferă servicii de îngrijire vârstnici într-un mediu familial și confortabil, în zona pitorească a Bucovinei. Personalul calificat asigură îngrijire personalizată, asistență medicală, mese regulate și activități recreative pentru seniori. Casa Seniorilor Viața Bună reprezintă o opțiune excelentă pentru familiile din județul Suceava care caută un cămin de bătrâni într-o locație cu aer curat și peisaje montane, ideal pentru îngrijire vârstnici de calitate.",

    "centrul-pentru-persoane-varstnice-cernavoda": "Centrul pentru persoane vârstnice Cernavodă din județul Constanța oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Răscoalei nr. 10, cu o notă de 3 stele pe Google, acest centru de îngrijire pentru seniori asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru vârstnici. Centrul pentru persoane vârstnice Cernavodă reprezintă o opțiune pentru familiile din județul Constanța care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale.",

    "centrul-de-zi-pentru-persoane-varstnice-perla": "Centrul de Zi pentru Persoane Vârstnice Perla din București oferă servicii de îngrijire vârstnici pe parcursul zilei, pentru seniori care preferă să locuiască acasă dar beneficiază de activități și supraveghere în timpul zilei. Situat pe Șoseaua Ștefan cel Mare nr. 1-3, cu o notă de 4.6 stele pe Google, acest centru de îngrijire pentru persoane vârstnice organizează activități recreative, socializare, mese și asistență medicală. Centrul de zi Perla reprezintă o resursă valoroasă pentru seniorii din București care doresc să mențină o viață activă și socială, beneficiind de îngrijire vârstnici de calitate într-un mediu familial.",

    "camin-pentru-persoane-varstnice-sf-gheorghe-gugesti": "Căminul pentru Persoane Vârstnice Sf. Gheorghe Gugești din județul Vrancea oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Acad. C-tin Toma nr. 28, cu o notă de 5 stele pe Google, acest centru de îngrijire pentru seniori asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru vârstnici. Căminul pentru Persoane Vârstnice Sf. Gheorghe din Gugești reprezintă o opțiune pentru familiile din județul Vrancea care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "ingrijiri-paliative-centrul-medical-galaxy-med": "Centrul Medical Galaxy Med din Craiova, județul Dolj, oferă servicii specializate de îngrijiri paliative pentru persoane vârstnice. Cu o notă de 4.3 stele din 16 recenzii pe Google, acest centru de îngrijire pentru seniori asigură îngrijire medicală, controlul durerii, suport emoțional și asistență pentru pacienți și familii. Personalul medical calificat oferă îngrijire vârstnici paliativă la standarde înalte, cu atenție la demnitate și confortul pacientului. Centrul Medical Galaxy Med reprezintă o resursă importantă pentru familiile din județul Dolj care caută îngrijire paliativă de calitate pentru persoane vârstnice în stadii avansate de boală.",

    "centrul-de-ingrijire-a-persoanelor-varstnice-ervin-med": "Centrul de Îngrijire a Persoanelor Vârstnice Ervin Med din Nanov, județul Teleorman, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Cu o notă de 5 stele pe Google, acest centru de îngrijire pentru seniori asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru vârstnici. Centrul Ervin Med reprezintă o opțiune pentru familiile din județul Teleorman care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale ale fiecărui rezident.",

    "azil-de-batrani-bucuresti-2": "Căminul de bătrâni din Balotești, județul Ilfov, oferă servicii de îngrijire vârstnici la doar 15 km de București. Situat pe Strada 1 Decembrie nr. 2, acest centru de îngrijire pentru persoane vârstnice asigură un mediu sigur și confortabil, cu personal calificat pentru îngrijirea rezidenților. Căminul de bătrâni oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și supraveghere permanentă. Pentru familiile din București și Ilfov care caută îngrijire vârstnici de calitate într-o locație accesibilă, acest centru de îngrijire din Balotești reprezintă o opțiune practică și convenabilă.",

    "camin-batrani-sf-ioachim-si-ana": "Căminul de bătrâni Sf. Ioachim și Ana din Mogoșoaia, județul Ilfov, oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Cu o notă de 5 stele pe Google, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Căminul de bătrâni Sf. Ioachim și Ana din Mogoșoaia reprezintă o opțiune excelentă pentru familiile din județul Ilfov care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atmosferă caldă și dedicare.",

    "centrul-pentru-seniori-merghindeal": "Centrul pentru Seniori Merghindeal din județul Sibiu oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Cu o notă de 5 stele din 3 recenzii pe Google, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul pentru Seniori Merghindeal reprezintă o opțiune pentru familiile din județul Sibiu care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect, într-o zonă liniștită și cu aer curat.",

    "fundatia-seniorenbetreuung": "Fundația Seniorenbetreuung din Deva, județul Hunedoara, oferă servicii de îngrijire vârstnici și asistență pentru persoanele vârstnice. Situată pe Bulevardul 22 Decembrie nr. 37, cu o notă de 5 stele pe Google, această fundație asigură îngrijire personalizată, asistență medicală și suport pentru seniori. Personalul calificat oferă îngrijire vârstnici la standarde înalte, cu atenție la demnitate și confortul rezidenților. Fundația Seniorenbetreuung reprezintă o opțiune pentru familiile din județul Hunedoara care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu misiune socială și dedicare.",

    "azilul-batranilor": "Căminul de bătrâni din Târgu Frumos, județul Iași, oferă servicii de îngrijire vârstnici pentru persoanele care au nevoie de asistență și supraveghere permanentă. Situat pe Strada Petu Rareș nr. 2, acest centru de îngrijire pentru seniori asigură un mediu familial și sigur, unde rezidenții primesc îngrijire personalizată din partea personalului calificat. Căminul de bătrâni din Târgu Frumos oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru vârstnici. Pentru familiile din județul Iași care caută îngrijire vârstnici de calitate, acest centru de îngrijire reprezintă o opțiune demnă de încredere.",

    "camin-de-batrani-voluntari": "Căminul de bătrâni din Voluntari, județul Ilfov, oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situat pe Strada Erou Iancu Nicolae nr. 22-24, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Căminul de bătrâni din Voluntari reprezintă o opțiune excelentă pentru familiile din zona Ilfov care caută îngrijire vârstnici de calitate într-o locație accesibilă din apropierea Bucureștiului.",

    "camin-de-batrani-pipera-ingrijire-batrani-alzheimer": "Căminul de bătrâni Pipera din Voluntari, județul Ilfov, oferă servicii specializate de îngrijire vârstnici, cu accent pe îngrijirea persoanelor cu Alzheimer și demență. Situat pe Strada Alexandru Ioan Cuza, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală specializată și supraveghere permanentă. Personalul calificat este instruit pentru a gestiona cazurile de Alzheimer, oferind un mediu sigur și confortabil pentru seniorii cu nevoi speciale. Căminul de bătrâni Pipera reprezintă o opțiune excelentă pentru familiile din județul Ilfov care caută îngrijire vârstnici specializată pentru Alzheimer și demență.",

    "centru-imgrijire-persoane-varstnice": "Centrul de Îngrijire Persoane Vârstnice din Voluntari, județul Ilfov, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Bulevardul Voluntari, acest centru de îngrijire pentru seniori asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru vârstnici. Centrul de Îngrijire Persoane Vârstnice din Voluntari reprezintă o opțiune pentru familiile din județul Ilfov care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale.",

    "camin-de-batrani-pantelimon-mazain": "Căminul de bătrâni Pantelimon-Mazain din București oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situat pe Strada Dimitrie Cantemir nr. 1, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Căminul de bătrâni Pantelimon-Mazain reprezintă o opțiune pentru familiile din București care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "caminul-de-batrani-sfpantelimon": "Căminul de bătrâni Sf. Pantelimon din Popești-Leordeni, județul Ilfov, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Unirii nr. 10, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Căminul de bătrâni Sf. Pantelimon reprezintă o opțiune pentru familiile din județul Ilfov care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atmosferă familială.",

    "caminul-de-batrani-santa-maria": "Căminul de bătrâni Santa Maria din Pantelimon, județul Ilfov, oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situat pe Strada Vâlcea nr. 6, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Căminul de bătrâni Santa Maria din Pantelimon reprezintă o opțiune pentru familiile din județul Ilfov care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "centru-ingrijire-batrani": "Centrul de îngrijire bătrâni din Desești, județul Maramureș, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil, în zona tradițională a Maramureșului. Acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul de îngrijire bătrâni din Desești reprezintă o opțiune pentru familiile din județul Maramureș care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la tradiții și comunitate.",

    "centrul-de-seniori-sabis": "Centrul de Seniori Sabis din Luduș, județul Mureș, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Bulevardul 1 Decembrie 1918 nr. 25, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul de Seniori Sabis din Luduș reprezintă o opțiune pentru familiile din județul Mureș care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale ale fiecărui rezident.",

    "centru-de-zi-pentru-primire-persoane-varstnice-dobra": "Centrul de zi pentru primire persoane vârstnice din Dobra, județul Hunedoara, oferă servicii de îngrijire vârstnici pe parcursul zilei. Acest centru de îngrijire pentru seniori organizează activități recreative, socializare, mese și asistență pentru vârstnicii care preferă să locuiască la domiciliu. Cu o notă de 5 stele pe Google, centrul pune accent pe crearea unei comunități active pentru seniorii din zona Dobra. Centrul de zi reprezintă o resursă valoroasă pentru familiile din județul Hunedoara care caută îngrijire vârstnici de calitate și activități sociale pentru persoanele vârstnice.",

    "caminul-de-pensionari": "Căminul de Pensionari din Rădăuți, județul Suceava, oferă servicii de îngrijire vârstnici pentru pensionari și persoane vârstnice care au nevoie de asistență. Situat pe Strada Volovățului nr. 50, acest centru de îngrijire pentru seniori asigură un mediu familial și sigur, cu personal calificat pentru îngrijirea rezidenților. Căminul de Pensionari oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative. Pentru familiile din județul Suceava care caută îngrijire vârstnici de calitate, acest centru de îngrijire din Rădăuți reprezintă o opțiune demnă de încredere.",

    "bloom-senior-living": "Bloom Senior Living din Someșul Rece, județul Cluj, oferă servicii premium de îngrijire vârstnici într-o locație excepțională, în zona montană a Apusenilor. Cu o notă de 5 stele pe Google, acest cămin de bătrâni privat asigură îngrijire personalizată, asistență medicală 24/7, mese regulate preparate din ingrediente proaspete și activități recreative pentru seniori. Bloom Senior Living pune accent pe demnitate, respect și confortul rezidenților, creând un mediu în care vârstnicii se pot simți ca acasă, înconjurati de natură și aer curat. Pentru familiile din județul Cluj care caută un cămin de bătrâni premium, Bloom Senior Living reprezintă o alegere de top.",

    "casa-milostivirii-divine-centrul-de-ingrijire-paliativa-de-tip-hospice": "Casa Milostivirii Divine din Timișoara, județul Timiș, este un centru de îngrijire paliativă de tip hospice pentru persoane vârstnice. Situat pe Strada Memorandului nr. 84, cu o notă de 4.8 stele pe Google, acest centru de îngrijire pentru seniori asigură îngrijire medicală specializată, controlul durerii, suport emoțional și asistență pentru pacienți și familii. Personalul medical calificat oferă îngrijire vârstnici paliativă la standarde înalte, cu atenție la demnitate și confortul pacientului. Casa Milostivirii Divine reprezintă o resursă importantă pentru familiile din județul Timiș care caută îngrijire paliativă de calitate pentru persoane vârstnice.",

    "centrul-varstnicului-sannicolau-mare": "Centrul Vârstnicului din Sânnicolau Mare, județul Timiș, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada 16 Decembrie 1989 nr. 45, cu o notă de 5 stele pe Google, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul Vârstnicului din Sânnicolau Mare reprezintă o opțiune excelentă pentru familiile din județul Timiș care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "casa-de-batrani-buzias-asociatia-casa-noua": "Casa de bătrâni Buziaș din județul Timiș, gestionată de Asociația Casa Nouă, oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situată pe Strada Principală nr. 200, în stațiunea balneară Buziaș, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Casa de bătrâni Buziaș reprezintă o opțiune excelentă pentru familiile din județul Timiș care caută îngrijire vârstnici de calitate într-o locație cu aer curat și atmosferă liniștită.",

    "camin-de-batrani-amalia": "Căminul de bătrâni Amalia din București oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situat pe Strada Jimbolia nr. 122, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Căminul de bătrâni Amalia reprezintă o opțiune pentru familiile din București care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atmosferă caldă și atenție la nevoile individuale.",

    "centrul-de-zi-pentru-persoane-varstnice-barlad": "Centrul de zi pentru persoane vârstnice din Bârlad, județul Vaslui, oferă servicii de îngrijire vârstnici pe parcursul zilei. Situat pe Strada Nicolae Tonitza nr. 7, acest centru de îngrijire pentru seniori organizează activități recreative, socializare, mese și asistență pentru vârstnicii care preferă să locuiască la domiciliu. Centrul de zi din Bârlad reprezintă o resursă valoroasă pentru familiile din județul Vaslui care caută îngrijire vârstnici de calitate și activități sociale pentru persoanele vârstnice, într-un mediu familial și sigur.",

    "azilul-de-batrani-speranta-la-viata": "Căminul de bătrâni Speranță la viață din Avrămești, județul Vaslui, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Cu o notă de 5 stele pe Google, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Căminul de bătrâni Speranță la viață reprezintă o opțiune pentru familiile din județul Vaslui care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "centrul-de-tip-familial-pentru-persoane-varstnice": "Centrul de tip familial pentru persoane vârstnice din Gârbova, județul Alba, oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situat pe Strada Creanga Ion nr. 497, acest centru de îngrijire pentru seniori asigură îngrijire personalizată, asistență medicală și supraveghere permanentă, într-un format de tip familial care creează o atmosferă caldă și apropiată de cea a casei. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru vârstnici. Centrul de tip familial din Gârbova reprezintă o opțiune pentru familiile din județul Alba care caută îngrijire vârstnici de calitate.",

    "raiul-santa-maria-casa-de-ingrijire-batrani": "Raiul Santa Maria din Petrăchioaia, județul Ilfov, este o casă de îngrijire pentru bătrâni care oferă servicii de îngrijire vârstnici într-un mediu familial și sigur. Situat pe Strada Măceșului nr. 114, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Raiul Santa Maria din Petrăchioaia reprezintă o opțiune pentru familiile din județul Ilfov care caută îngrijire vârstnici de calitate într-o locație liniștită aproape de București.",

    "centrul-de-ingrijire-de-zi-aiud": "Centrul de Îngrijire de Zi Aiud din județul Alba oferă servicii de îngrijire vârstnici pe parcursul zilei, pentru seniori care preferă să locuiască la domiciliu. Situat pe Strada Unirii nr. 1, acest centru de îngrijire pentru persoane vârstnice organizează activități recreative, socializare, mese și asistență medicală. Personalul calificat oferă supraveghere și asistență pentru vârstnicii din Aiud și imprejurimi. Centrul de zi din Aiud reprezintă o resursă valoroasă pentru familiile din județul Alba care caută îngrijire vârstnici de calitate și activități sociale pentru persoanele vârstnice.",

    "centrul-de-ingrijire-si-asistenta-garbova": "Centrul de Îngrijire și Asistență Gârbova din județul Alba oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Creanga Ion nr. 478, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Gârbova reprezintă o opțiune pentru familiile din județul Alba care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale.",

    "serviciul-de-ingrijire-la-domiciliu": "Serviciul de Îngrijire la Domiciliu din Cugir, județul Alba, oferă servicii de îngrijire vârstnici la domiciliu pentru persoanele care preferă să rămână în propriul cămin. Situat pe Strada Nicolae Grigorescu nr. 3, acest centru de îngrijire pentru seniori asigură asistență personalizată, ajutor în activitățile zilnice, administrarea medicației și supraveghere. Serviciul de îngrijire la domiciliu din Cugir oferă flexibilitate și confort pentru vârstnici, permițându-le să mențină independența beneficiind totodată de îngrijire vârstnici profesionistă. Pentru familiile din județul Alba care caută îngrijire vârstnici la domiciliu, acest serviciu reprezintă o soluție practică și de încredere.",

    "centrul-de-ingrijire-terapie-si-recuperare": "Centrul de Îngrijire, Terapie și Recuperare din Lipova, județul Arad, oferă servicii de îngrijire vârstnici și recuperare medicală pentru persoanele vârstnice. Situat pe Strada Lugojului nr. 6, acest centru de îngrijire pentru seniori asigură îngrijire personalizată, asistență medicală, terapie și recuperare. Personalul calificat oferă mese regulate, administrarea medicației, kinetoterapie și activități recreative pentru vârstnici. Centrul din Lipova reprezintă o opțiune pentru familiile din județul Arad care caută îngrijire vârstnici de calitate cu componentă de recuperare medicală.",

    "centrul-de-ingrijire-de-zi-curtici": "Centrul de îngrijire de zi Curtici din județul Arad oferă servicii de îngrijire vârstnici pe parcursul zilei. Situat pe Strada Revoluției nr. 36A, cu o notă de 4.6 stele pe Google, acest centru de îngrijire pentru persoane vârstnice organizează activități recreative, socializare, mese și asistență pentru seniorii care preferă să locuiască la domiciliu. Personalul calificat oferă supraveghere și asistență pentru vârstnicii din Curtici și imprejurimi. Centrul de zi din Curtici reprezintă o resursă valoroasă pentru familiile din județul Arad care caută îngrijire vârstnici de calitate.",

    "centru-de-ingrijire-si-asistenta-pecica": "Centrul de Îngrijire și Asistență Pecica din județul Arad oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada 2 nr. 199, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Pecica reprezintă o opțiune pentru familiile din județul Arad care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale.",

    "centrul-de-ingrijire-si-asistenta-pitesti": "Centrul de Îngrijire și Asistență Pitești din județul Argeș oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Aleea George Stephănescu nr. 5, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Pitești reprezintă o opțiune pentru familiile din județul Argeș care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "centrul-de-ingrijire-luxab-sector-6": "Centrul de îngrijire LUXAB Sector 6 din București oferă servicii profesionale de îngrijire vârstnici într-o locație accesibilă pe Drumul Ciorogârla nr. 371D. Face parte din rețeaua LUXAB, recunoscută pentru standardele ridicate de îngrijire pentru persoane vârstnice. Personalul calificat asigură asistență medicală 24/7, mese regulate, administrarea tratamentului și activități recreative pentru seniori. Centrul de îngrijire LUXAB din Sector 6 reprezintă o opțiune excelentă pentru familiile din București care caută un cămin de bătrâni de încredere, cu accent pe demnitate, respect și îngrijire personalizată.",

    "centrul-de-ingrijire-la-domiciliu-pargaresti": "Centrul de Îngrijire la Domiciliu Pârgărești din județul Bacău, gestionat de Caritas Iași, oferă servicii de îngrijire vârstnici la domiciliu pentru persoanele care preferă să rămână în propriul cămin. Situat pe Strada Mărului nr. 50, cu o notă de 4.8 stele pe Google, acest centru de îngrijire pentru seniori asigură asistență personalizată, ajutor în activitățile zilnice, administrarea medicației și supraveghere. Centrul de îngrijire la domiciliu din Pârgărești oferă flexibilitate și confort pentru vârstnici, permițându-le să mențină independența. Pentru familiile din județul Bacău care caută îngrijire vârstnici la domiciliu, acest serviciu reprezintă o soluție de încredere.",

    "centrul-de-ingrijire-si-asistenta-sf-dimitrie": "Centrul de Îngrijire și Asistență Sf. Dimitrie din București oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Șoseaua Berceni nr. 12, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Sf. Dimitrie reprezintă o opțiune pentru familiile din București care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "centrul-de-ingrijire-si-asistenta-casa-maria": "Centrul de Îngrijire și Asistență Casa Maria din Voluntari, județul Ilfov, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Bulevardul Eroilor nr. 96, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul Casa Maria din Voluntari reprezintă o opțiune pentru familiile din județul Ilfov care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atmosferă familială.",

    "centrul-de-ingrijire-si-asistenta-pentru-persoane-adulte": "Centrul de Îngrijire și Asistență pentru Persoane Adulte din București oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Calea Vitan nr. 267-269, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul din zona Vitan reprezintă o opțiune pentru familiile din București care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale.",

    "centrul-rezidential": "Centrul rezidențial din Făurei, județul Brăila, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Mecanizatorilor nr. 4, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul rezidențial din Făurei reprezintă o opțiune pentru familiile din județul Brăila care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "otopeni-residence-reteaua-affinity": "Otopeni Residence din județul Ilfov face parte din rețeaua Affinity de cămine de bătrâni premium. Situat pe Strada Lucian Blaga din Otopeni, acest centru de îngrijire pentru persoane vârstnice oferă servicii de îngrijire vârstnici la standarde ridicate, într-o locație accesibilă din apropierea Bucureștiului. Otopeni Residence asigură îngrijire personalizată, asistență medicală 24/7, mese regulate și activități recreative pentru seniori. Rețeaua Affinity este recunoscută pentru profesionalismul și calitatea serviciilor de îngrijire vârstnici. Pentru familiile din județul Ilfov care caută un cămin de bătrâni premium, Otopeni Residence reprezintă o alegere de top.",

    "centrul-de-ingrijire-si-asistenta-carei": "Centrul de Îngrijire și Asistență Carei din județul Satu Mare oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Vlahuță nr. 1, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Carei reprezintă o opțiune pentru familiile din județul Satu Mare care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "centrul-de-ingrijire-si-asistenta-agnita": "Centrul de Îngrijire și Asistență Agnita din județul Sibiu oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Mihai Viteazul nr. 16-18, în vechea Primărie, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Agnita reprezintă o opțiune pentru familiile din județul Sibiu care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale.",

    "asezamantul-de-asistenta-sociala-sfantul-andrei": "Așezământul de Asistență Socială Sfântul Andrei din Fălticeni, județul Suceava, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Matei Milo, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Așezământul Sfântul Andrei din Fălticeni reprezintă o opțiune pentru familiile din județul Suceava care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu misiune socială și dedicare.",

    "asociatia-umanitara-centrul-rezidential-bucovina": "Asociația Umanitară Centrul Rezidențial Bucovina din Câmpulung Moldovenesc, județul Argeș, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada 28 Noiembrie, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul Rezidențial Bucovina reprezintă o opțiune pentru familiile din județul Argeș care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu misiune umanitară.",

    "centrul-de-ingrijire-si-asistenta-babadag": "Centrul de Îngrijire și Asistență Babadag din județul Tulcea oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Heracleea, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Babadag reprezintă o opțiune pentru familiile din județul Tulcea care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la demnitate și respect.",

    "centrul-de-ingrijire-si-asistenta-pausesti-maglasi": "Centrul de Îngrijire și Asistență Păușești-Măglași din județul Vâlcea oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat în localitatea Păușești-Măglași, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul de Îngrijire și Asistență Păușești-Măglași reprezintă o opțiune pentru familiile din județul Vâlcea care caută îngrijire vârstnici de calitate într-un centru de îngrijire cu atenție la nevoile individuale.",

    "centrul-de-ingrijire-si-asistenta-sf-elena": "Centrul de Îngrijire și Asistență Sf. Elena din București, gestionat de DGASPC Sector 1, oferă servicii de îngrijire vârstnici într-un mediu sigur și confortabil. Situat pe Strada Barbu Delavrancea nr. 26, acest centru de îngrijire pentru persoane vârstnice asigură îngrijire personalizată, asistență medicală și supraveghere permanentă. Personalul calificat oferă mese regulate, administrarea medicației, asistență în activitățile zilnice și activități recreative pentru seniori. Centrul Sf. Elena reprezintă o opțiune pentru familiile din București care caută îngrijire vârstnici de calitate într-un centru de îngrijire public cu atenție la demnitate și respect.",
}

def main():
    # Load existing descriptions
    existing = json.loads(DESC_FILE.read_text())
    print(f"Existing descriptions: {len(existing)}")

    # Add new descriptions
    added = 0
    for slug, desc in DESCRIPTIONS.items():
        if slug in existing:
            print(f"  ⚠️  Already exists: {slug}")
            continue
        existing[slug] = desc
        added += 1

    # Save
    DESC_FILE.write_text(json.dumps(existing, ensure_ascii=False, indent=2))
    print(f"\nAdded: {added}")
    print(f"Total descriptions: {len(existing)}")

    # Verify all 77 have descriptions
    new = json.loads((REPO / "src" / "data" / "camine-new-found.json").read_text())
    missing = [c["slug"] for c in new if c["slug"] not in existing]
    if missing:
        print(f"\n⚠️  Missing descriptions ({len(missing)}):")
        for s in missing:
            print(f"  - {s}")
    else:
        print(f"\n✅ All {len(new)} new entries have descriptions!")


if __name__ == "__main__":
    main()
